name: Postman API Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run tests/postman/collection.json -e tests/postman/environment.json \
          --reporters cli,html \
          --reporter-html-export report.html

      - name: Upload HTML Report
  uses: actions/upload-artifact@v4
  with:
    name: postman-report
    path: report.html