name: Postman API Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-postman:
    runs-on: ubuntu-latest
    services:
      backend:
        image: your-backend-image:latest
        ports:
          - 8084:8084
        options: >-
          --health-cmd="curl -f http://localhost:8084/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Wait for backend to be healthy
        run: |
          echo "Waiting for backend to be ready..."
          until curl -s http://localhost:8084/health; do sleep 5; done

      - name: Run Postman Collection
        run: |
          newman run tester/postman/recev_account_detail.postman_collection.json \
          --reporters cli,html \
          --reporter-html-export report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: report.html